version: '3'

services:
  postgres:
    image: 'postgres:12'
    container_name: reportify_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: reportify_db
      POSTGRES_USER: reportify_db_user
      POSTGRES_PASSWORD: reportify_db_pwd
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  django:
    build: .
    container_name: reportify_app
    restart: unless-stopped
    command: >
      bash -c "python ./manage.py makemigrations &&
                ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/opt/projects/reportify
    ports:
      - '8000:8000'
    depends_on:
      - postgres

volumes:
  postgres_data:
