# Generated by Django 4.2.7 on 2024-02-09 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_status_report_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=20, null=True
            ),
        ),
    ]
